Merged PR 4343: Fix the build issues faced with Crypto unit test
Getting build error with unittest build.
/__w/1/s/cerberus/core/testing/crypto/ecdsa_test.c: In function 'ecdsa_test_verify_message_p521_sha512':
/__w/1/s/cerberus/core/testing/crypto/ecdsa_test.c:2236:2: error: expected ';' before 'ecdsa_testing_release_dependencies'
 2236 |  ecdsa_testing_release_dependencies (test, &ecdsa);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/1/s/cerberus/core/testing/crypto/ecdsa_test.c: In function 'ecdsa_test_verify_message_p521_sha512_private_key':
/__w/1/s/cerberus/core/testing/crypto/ecdsa_test.c:2261:2: error: expected ';' before 'ecdsa_testing_release_dependencies'
 2261 |  ecdsa_testing_release_dependencies (test, &ecdsa);

Following fixes made.
1) /core/testing/crypto/ecdsa_test.c - added missing semicolons
2) /core/testing/crypto/kat/ecdsa_kat_test.c - moved test "ecdsa_kat_test_run_self_test_ecc_hw_sign_p521_sha512" under #if (defined HASH_ENABLE_SHA512) && (ECC_MAX_KEY_LENGTH >= ECC_KEY_LENGTH_521)

----
#### AI description  (iteration 1)
#### PR Classification
Bug fix

#### PR Summary
This pull request addresses build issues in the `unittest` by making necessary code adjustments and fixes.
- `ecdsa_kat_test.c`: Re-enabled the `ecdsa_kat_test_run_self_test_ecc_hw_sign_p521_sha512` test under the correct preprocessor conditions.
- `ecdsa_test.c`: Added missing semicolons in multiple test functions to fix syntax errors.

Related work items: #4701