Merged PR 5349: Init a variable to prevent warning with -flto
Init a variable to prevent warning with -flto

If the project is compiled with `-flto` option
the build fails on an error:

```
mctp_interface.c:856:7: error: 'msg_type' may be used uninitialized in
this function [-Werror=maybe-uninitialized]
  856 |    if (!mctp_interface_is_expected_response (mctp, msg_tag, som,
msg_type)) {
      |       ^
cerberus/core/mctp/mctp_interface.c:827:10: note:
'msg_type' was declared here
  827 |  uint8_t msg_type;
      |          ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error
```
In CMakeLists.txt this setting is add to add LTO
`set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)`

----
#### AI description  (iteration 1)
#### PR Classification
Code cleanup to prevent compiler warnings during link time optimization.

#### PR Summary
This pull request initializes the previously uninitialized variable to silence warnings when compiling with -flto.
- In `/core/mctp/mctp_interface.c`, `msg_type` is now explicitly initialized to 0 in the `mctp_interface_process_packet` function.
<!-- GitOpsUserAgent=GitOps.Apps.Server.pullrequestcopilot -->